import type { WorkbenchRunView } from "./types.js";

export function buildDemoPipelineRun(): WorkbenchRunView {
  return {
    id: "demo-pipeline",
    source: "demo",
    label: "Demo · pipeline automation",
    status: "blocked",
    prompt: "修复测试环境中订单创建后详情页白屏的问题，并完成一次验证闭环。",
    startedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    completedAt: new Date().toISOString(),
    provider: "openai",
    model: "gpt-5.1",
    metrics: [
      { label: "Status", value: "blocked", tone: "warning" },
      { label: "Provider", value: "openai", tone: "accent" },
      { label: "Model", value: "gpt-5.1", tone: "neutral" },
      { label: "Tokens", value: "18240", tone: "neutral" },
      { label: "Tools", value: "11", tone: "neutral" },
      { label: "Human Review", value: "needed", tone: "warning" },
    ],
    stages: [
      {
        id: "intake",
        title: "Intake",
        status: "success",
        summary: "需求被解析为测试环境修复任务。",
        detail: "Agent 识别到这是一个 incident + deployment 风险混合型任务。",
      },
      {
        id: "context",
        title: "Context",
        status: "success",
        summary: "读取了部署手册、历史问题记忆和目标页面说明。",
        detail: "知识库命中 deployment-playbook 与 incident-response。",
      },
      {
        id: "execution",
        title: "Execution",
        status: "success",
        summary: "完成改代码、触发 CI 和部署测试环境。",
        detail: "CI 首次失败后，Agent 根据测试报告修复了一个空值判断问题。",
      },
      {
        id: "review",
        title: "Review",
        status: "blocked",
        summary: "点击测试通过，但日志侧仍有新增 warning，需要人工确认是否放行。",
        detail: "当前停在 human-on-the-loop 的确认点。",
      },
      {
        id: "finalize",
        title: "Finalize",
        status: "blocked",
        summary: "已生成修复结论，但仍建议观察日志趋势。",
        detail: "系统没有继续自动推进到更高风险环境。",
      },
    ],
    activities: [
      {
        id: "demo_1",
        timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        category: "run",
        title: "Run started",
        detail: "接收缺陷描述并建立修复 run。",
        status: "info",
      },
      {
        id: "demo_2",
        timestamp: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
        category: "context",
        title: "Task parsed",
        detail: "识别为 incident + deployment 任务，优先走 reasoning 模型。",
        status: "success",
      },
      {
        id: "demo_3",
        timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        category: "tool",
        title: "create_branch · success",
        detail: "创建分支 fix/order-detail-blank-screen。",
        status: "success",
      },
      {
        id: "demo_4",
        timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
        category: "tool",
        title: "trigger_pipeline · failed",
        detail: "首轮 CI 因测试快照不一致失败。",
        status: "error",
      },
      {
        id: "demo_5",
        timestamp: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
        category: "system",
        title: "Run retrying",
        detail: "读取失败报告后生成补丁并重试验证。",
        status: "warning",
      },
      {
        id: "demo_6",
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        category: "tool",
        title: "run_click_test · success",
        detail: "订单创建 -> 跳转详情页 -> 页面正常渲染。",
        status: "success",
      },
      {
        id: "demo_7",
        timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
        category: "approval",
        title: "Approval requested",
        detail: "日志新增 warning 是否接受，需要人工确认。",
        status: "warning",
      },
    ],
    tools: [
      { name: "create_branch", latestStatus: "success", count: 1, lastDetail: "新建缺陷修复分支。" },
      { name: "apply_code_patch", latestStatus: "success", count: 2, lastDetail: "两次修复 patch 已应用。" },
      { name: "trigger_pipeline", latestStatus: "success", count: 2, lastDetail: "第二轮 CI 已通过。" },
      { name: "query_seq_logs", latestStatus: "success", count: 1, lastDetail: "聚合了本次部署后的 warning。" },
      { name: "run_click_test", latestStatus: "success", count: 1, lastDetail: "真实浏览器点击验证通过。" },
    ],
    approvals: [
      { id: "approval_demo_warning_check", title: "是否接受新增 warning 并继续推进", status: "pending" },
    ],
    pipeline: {
      title: "Validation Pipeline",
      provider: "github-actions",
      status: "passed",
      summary: "第二轮 CI 已通过，失败 job 已被自动分析和修复。",
      branch: "fix/order-detail-blank-screen",
      commitSha: "8fd21a4",
      jobs: [
        { name: "typecheck", status: "passed" },
        { name: "unit-tests", status: "passed" },
        { name: "smoke-tests", status: "passed" },
      ],
    },
    logs: {
      title: "Log Insight",
      provider: "seq",
      status: "warning",
      summary: "error 已消失，但本次部署后仍出现少量重复 warning。",
      highlights: [
        "OrderDetailView 的 null reference error 不再出现。",
        "发现 3 条新的 warn: missing optional customer note。",
        "warning 未阻塞功能，但建议观察 1 个版本周期。",
      ],
    },
    browserTest: {
      title: "Click Test",
      provider: "playwright",
      status: "passed",
      scenario: "创建订单后进入详情页",
      summary: "用户路径已经能正常点通，详情页渲染恢复正常。",
      screenshots: ["before.png", "after.png"],
      artifacts: ["trace.zip", "console.log", "network-summary.json"],
    },
    finalReport: {
      summary: "测试环境修复已完成，功能路径通过点击测试，但日志侧仍建议人工确认 warning 接受度。",
      answer:
        "Agent 已完成代码修复、CI 重试、测试环境部署和点击验证。当前建议由人工确认新增 warning 是否可接受，再决定是否继续推进。",
      risks: ["仍有少量 warning，需要确认是否属于可接受噪音。"],
      nextSteps: ["人工确认 warning 策略。", "如可接受，再执行后续环境推进。"],
      citations: ["Seq summary", "CI run #1042", "Playwright trace"],
      needsHumanReview: true,
    },
  };
}
